version: "3"
services:
  nonebot:
    image: starheart/botfoochan:latest
    env_file:
      - .env
    environment:
      - ENVIRONMENT=prod
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8086}
      - MAX_WORKERS=1 # maximum workers
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    restart: always
