version: "3"
services:
  nonebot:
    image: starheart/botfoochan:latest
    environment:
      - ENVIRONMENT=prod
      - LOG_LEVEL=INFO
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8086}
      - SUPERUSERS=[]
      - MAX_WORKERS=1 # maximum workers
    ports:
      - "8086:${PORT:-8086}"
    volumes:
      - ".env.prod:/app/.env.prod"
      - "./data:/app/data"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    restart: always
