"""init user memory table

迁移 ID: 517252fe1927
父迁移:
创建时间: 2026-08-11 22:13:37.093707

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "517252fe1927"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("user_memory",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_memory",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_memory")),
        info={"bind_key": "user_memory"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_memory")
    # ### end Alembic commands ###
